spring:
  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:file:./data/database/test
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher